### ISSUE TITLE
Текстовый квест 

### ISSUE THREAD

**Issue by Avalan4er** [veyner/Project4#3]
Суть игры: строгих принципов нет, это может быть как линейный сюжет, требующий минимальных действий от игрока, так и полностью интерактивная забава, где количество возможных исходов исчисляется десятками. Классический пример первого типа — телевизионное шоу «Кто хочет стать миллионером?», второго типа — настольная игра Dungeons & Dragons. 

Чем полезно: Текстовые квесты — отличная тренировка для начинающего программиста. В них есть всё, что нужно: просчёт вероятности, оперирование данными и прогнозирование дальнейших действий. Можно обойтись и без этого, но в любом случае придётся научиться работать с классами, объектами и модулями. 

Как усложнить: импровизируйте!

**Comment by veyner** [comment]
1. На экране появлялся вопрос и варианты ответов
2.В зависимости от того какой вариант выбран отображалась разная ветка сюжета
3.Сюжет загружать из текстового файла формата .json
4.Возможность сохранить и продолжить игру

**Comment by veyner** [comment]
5. Каждый вариант выбора начисляет какие-то баллы, в последующий арках открываются дополнительные варианты выбора в зависимости от набранных баллов
6. Возможность скипать уже просмотренные арки до следующего выбора
